// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	  int N = Integer.parseInt(args[0]); // number of random numbers to generate
	  int countB=0;
	  int countS=0;
	  for (int i=0; i<N; i++) {
		  double r = Math.random();
		  if (r > 0.5) countB++;
		  else{
			countS++;
		  }
	  }
	double ratio = (double) countB/countS;
	System.out.println(" > 0.5:  " + countB + " times" );
	System.out.println(" <= 0.5: " + countS + " times" );
	if (! (countB==0 || countS==0 ) ) {
			System.out.println(" Ratio:  " + ratio );	
	}
	
	}
}
